package com.personal.budget.domain

import com.personal.budget.domain.model.MonthKey
import com.personal.budget.domain.usecase.NetWorthMath
import com.personal.budget.domain.usecase.Totals
import com.personal.budget.domain.usecase.YearColumn
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.double
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Asserts every number in docs/fixtures/expected.json (generated by tools/reference_calc.py
 * from docs/fixtures/sample-backup.json) against the Kotlin implementation of DOMAIN_RULES.md.
 */
class FixtureExpectedTest {
    private val expected: JsonObject = Json.parseToJsonElement(Fixtures.text("expected.json")).jsonObject
    private val book = Fixtures.book()
    private val file = Fixtures.backup.withoutDeleted()
    private val settings = file.settings!!.toDomain()
    private val eps = 1e-6

    private fun num(o: JsonObject, key: String) = o.getValue(key).jsonPrimitive.double

    private fun assertTotals(where: String, exp: JsonObject, actual: Totals) {
        assertEquals("$where income", num(exp, "income"), actual.income, eps)
        assertEquals("$where expenses", num(exp, "expenses"), actual.expenses, eps)
        assertEquals("$where saved", num(exp, "saved"), actual.saved, eps)
        assertEquals("$where contributions", num(exp, "contributions"), actual.contributions, eps)
        assertEquals("$where leftover", num(exp, "leftover"), actual.leftover, eps)
    }

    @Test
    fun months_matchExpected() {
        val months = expected.getValue("months").jsonObject
        assertEquals(book.months.size, months.size)
        var checkedCategories = 0
        for ((id, value) in months) {
            val o = value.jsonObject
            val (y, m) = id.split("-").map { it.toInt() }
            val key = MonthKey(y, m)
            val summary = book.monthSummary(key)
            assertEquals("$id closed", o.getValue("closed").jsonPrimitive.boolean, summary.closed)
            for ((catName, catValue) in o.getValue("categories").jsonObject) {
                val c = book.categories.single { it.name == catName }
                val co = catValue.jsonObject
                assertEquals("$id $catName expected", num(co, "expected"), book.expected(key, c.id), eps)
                val a = co.getValue("actual")
                if (a is JsonNull) {
                    assertNull("$id $catName actual should be blank", book.actual(key, c.id))
                } else {
                    val got = book.actual(key, c.id)
                    assertNotNull("$id $catName actual", got)
                    assertEquals("$id $catName actual", a.jsonPrimitive.double, got!!, eps)
                }
                checkedCategories++
            }
            assertTotals("$id expected", o.getValue("expected").jsonObject, summary.expected)
            assertTotals("$id actual", o.getValue("actual").jsonObject, summary.actual)
        }
        assertEquals(3 * 8, checkedCategories)
    }

    private fun assertColumn(where: String, exp: JsonObject, col: YearColumn) {
        assertTotals(where, exp, col.totals)
        assertEquals("$where annualized", num(exp, "annualized_savings"), col.annualizedSavings, 1e-4)
        assertEquals("$where pct_net", num(exp, "pct_net"), col.pctNetIncome!!, 1e-6)
        assertEquals("$where pct_gross", num(exp, "pct_gross"), col.pctGrossIncome!!, 1e-6)
        for ((catName, v) in exp.getValue("categories").jsonObject) {
            val c = book.categories.single { it.name == catName }
            assertEquals("$where $catName", v.jsonPrimitive.double, col.perCategory.getValue(c.id), eps)
        }
    }

    @Test
    fun years_matchExpected() {
        val years = expected.getValue("years").jsonObject
        assertEquals(listOf(2025, 2026), book.years())
        for ((y, value) in years) {
            val summary = book.yearSummary(y.toInt(), settings)
            assertNotNull(summary)
            val o = value.jsonObject
            assertColumn("$y expected", o.getValue("expected").jsonObject, summary!!.expected)
            assertColumn("$y actual", o.getValue("actual").jsonObject, summary.actual)
        }
    }

    @Test
    fun year_withNoMonths_isEmpty() {
        assertNull(book.yearSummary(2030, settings))
    }

    @Test
    fun netWorth_matchesExpected() {
        val nw = expected.getValue("net_worth").jsonObject
        val accounts = file.accounts.map { it.toDomain() }
        val ledger = file.ledgerEntries.map { it.toDomain() }
        val result = NetWorthMath.compute(book, accounts, ledger)
        val expAccounts = nw.getValue("accounts").jsonObject
        assertEquals(expAccounts.keys, accounts.filter { it.id in result.balances }.map { it.name }.toSet())
        for ((name, v) in expAccounts) {
            val a = accounts.single { it.name == name }
            assertEquals("account $name", v.jsonPrimitive.double, result.balances.getValue(a.id), eps)
        }
        assertEquals(num(nw, "net_reconciliations"), result.netReconciliations, eps)
        assertEquals(num(nw, "net_worth"), result.netWorth, eps)
        assertEquals(num(nw, "super_liquid"), result.superLiquid, eps)
    }

    @Test
    fun ledgerOverride_isFlagged_andDeletedRowsIgnored() {
        val key = MonthKey(2025, 11)
        val paychecks = book.categories.single { it.name == "Paychecks" }
        val line = book.line(key, paychecks)
        assertTrue("typed actual on a ledger category is an override", line.overridden)
        assertEquals(4050.0, line.ledgerSum, eps)
        val fun_ = book.categories.single { it.name == "Fun" }
        assertEquals("deleted 999 row ignored, refund counts", 150.0, book.ledgerSum(key, fun_.id), eps)
    }
}
